version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: your_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: rating
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_and_dump.sh:/docker-entrypoint-initdb.d/init_and_dump.sh:rw

volumes:
  postgres_data: